export const sensorActor: any = {
  P01: 'PVA_yield',
  B01: 'T_coll_infeed',
  B02: 'T_coll_backfeed',
  B03: 'T_coll_surface',
  B04: 'T_tank',
  B05: 'p_pump',
  B06: 'p_roof',
  B08: 'T_tank_2',
  B09: 'T_coll_Backfeed_2',
  B10: 'T_Coll_surface_2',
  B11: 'Mounting_height_level_sensor',
  'M01:Y1': 'f_pump',
  'M01:S1': 'Enable_pump',
  'M01:D1': 'Overheat_pump',
  F01: 'Level_tank_min',
  F02: 'Level_coll_full',
  'overheat_ pump_Sk': 'overheat_ pump_Sk',
  // B01: 'T_top_strat_tank',
  // B02: 'T_bottom_strat_tank',
  T_backfeed_Prim_SV: 'T_backfeed_Prim_SV',
  T_backfeed_sec_SV: 'T_backfeed_sec_SV',
  // F01: 'Flow_SV',
  // 'M01:D1': 'M01:D1',
  // 'M01:S1': 'SV_pump_on',
  Y01: 'Position_SV_mixing_valve',
  'P01_1 (T_infeed)': 'SV_T_infeed',
  'P01_2 (T_outfeed)': 'SV_T_outfeed',
  'P01_3 (flow)': 'SV_flow',
  'P01_4 (heat)': 'SV_heat',
  P_PUMP: 'P_PUMP',
  Flow_SV: 'Flow_SV',
  // B01: 'T_outside',
  // B02: 'Irradiation',
  // B03: 'Wind_Speed',
  T_backfeed_prim_wv: 'T_backfeed_prim_wv',
  T_infeed_sec_wv: 'T_infeed_sec_wv',
};
